name: nicobako-github-io

services:
  web:
    container_name: nicobako-github-io-web
    build:
      context: .
      dockerfile: Dockerfile
      target: web-server
    ports:
      - "8080:8080"
    develop:
      watch:
        - action: sync
          path: ./output
          target: /app
  jinja:
    container_name: nicobako-github-io-jinja
    build:
      context: .
      dockerfile: Dockerfile
      target: jinja-builder
    command: python build.py
    stdin_open: true # -i
    tty: true # -t
    develop:
      watch:
        - action: sync+restart
          path: ./build.py
          target: /app/build.py
        - action: sync+restart
          path: ./templates
          target: /app/templates
    volumes:
      - type: bind
        source: ./output
        target: /app/output
# volumes:
#   jinja-output:

